# Site settings
title: Kitz
email: mazjaleel@gmail.com
url: http://kitz.io
description: "Kitz is a collection of frameworks written in Swift. It includes small, self-contained, tested, high-quality frameworks, including statically typed Key-value store, managing NSNotificationCenter, launching and deeplinking into external applications, and much more!"
skills: "Cross-platform  •  Full Test Coverage  •  Modular"
meta_author: Jaleel Maz

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: disqus

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: swiftkitz

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c63e2c #80B3FF
  primary-rgb: "198,62,44" #"128,179,255"
  secondary: af0202 #FD6E8A
  secondary-dark: 700101 #A2122F

# Footer settings
footer:
  copyright: Kitz
  location: Spread the Word
  social: Check us out on Github
  credits: Contribute

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/SwiftKitz

# Postal address (add as many lines as necessary)
address:
  - line: Use Kitz in your apps
  - line: Share it with others

# Credits content
credits: 'Help us build build Kitz by opening issues and submitting PRs'

# Build settings
markdown: kramdown
permalink: pretty
